# Generated by Django 4.2.16 on 2024-09-04 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1e8bfb89-1885-4a8b-8f64-d2ad9c42477b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1e8bfb89-1885-4a8b-8f64-d2ad9c42477b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
